sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:
  wechat:
    appid: wx54b6abe48e07eb2b
    secret: 953533f261e555fc79bc864fc2f16fdb
    mchid: 1561414331
    mchSerialNo: 4B83D3C5414A5D817355BAF8D9EC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK5123645wxpay435434323FFDu3
    weChatPayCertFilePath: D:\pay\wechatpay_16D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://6619cf50.r6.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://6619cf50.r6.cpolar.top/notify/refundSuccess
